CREATE DATABASE products;
CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    product_name VARCHAR(30) NOT NULL,
    quanity INTEGER NOT NULL,
    price DECIMAL(20) NOT NULL
);
